### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by emergent-reasons**
@zquestz, @checksum0 and I did a number of fixes and formatting changes to his translation on this branch. I got a quick language review but am waiting for a more thorough one within the next day or so.

Sorry the commit history is dirty. Especially I'm not sure what happened with `modify2`. If it is important, I can work to get rid of that.

### CODE REVIEW

**Review by zquestz — APPROVED** [review]

**Comment by zquestz** [comment]
This ready to merge? Have we had one more french speaker check the translation?

**Comment by 3even** [comment]
Looks good. My one issue is with the term "Quickstart". Would "Démarrage rapide" be a better fit than "Bien commencer"?

**Comment by checksum0** [comment]
> Looks good. My one issue is with the term "Quickstart". Would "Démarrage rapide" be a better fit than "Bien commencer"?

Hey, it has already been changed a few commit later.

**Comment by zquestz** [comment]
This ready to go?

**Comment by emergent-reasons** [comment]
It's ready.

**Pull request merged**
