### PR TITLE
Added pt localization

### PR DESCRIPTION
**Pull request by m4ktub**
Changes:

* New `pt.yml` localization
* Updated i18n modal with new language entry
* Updated Gruntfile to generate `/pt/` version
* Rebuilt site with `grunt live`

### CODE REVIEW

**Comment by emergent-reasons** [comment]
@zquestz This LGTM when you are ready for review.

**Comment by emergent-reasons** [comment]
@zquestz Forgot to mention @m4ktub has put out a request for review. We can wait a while for that.

**Review by zquestz — APPROVED** [review]

**Comment by zquestz** [comment]
This ready to merge? Happy to do that =)

**Comment by m4ktub** [comment]
Ideally it should be reviewed by someone. I've tried to make it `pt`
instead of `pt-PT` but that's a though balance.

**Comment by zquestz** [comment]
Any suggestions on a good person to review?

**Comment by m4ktub** [comment]
No one in particular. I've tried to contact people today so it's best to wait at least a couple of days.

**Comment by zquestz** [comment]
Been a few days? Anyone else checked this yet?

**Comment by m4ktub** [comment]
Yes, you're right. I couldn't get anyone to review this translation. I'll leave the merge at your discretion.

**Pull request merged**
